apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mbole-pay.fullname" . }}-secrets
  labels:
    {{- include "mbole-pay.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required ".Values.secrets.DATABASE_URL is required" .Values.secrets.DATABASE_URL | quote }}
  NEXTAUTH_SECRET: {{ required ".Values.secrets.NEXTAUTH_SECRET is required" .Values.secrets.NEXTAUTH_SECRET | quote }}
  EMAIL_USER: {{ required ".Values.secrets.EMAIL_USER is required" .Values.secrets.EMAIL_USER | quote }}
  EMAIL_PASSWORD: {{ required ".Values.secrets.EMAIL_PASSWORD is required" .Values.secrets.EMAIL_PASSWORD | quote }}
  FAPSHI_API_KEY: {{ required ".Values.secrets.FAPSHI_API_KEY is required" .Values.secrets.FAPSHI_API_KEY | quote }}
  FAPSHI_WEBHOOK_SECRET: {{ required ".Values.secrets.FAPSHI_WEBHOOK_SECRET is required" .Values.secrets.FAPSHI_WEBHOOK_SECRET | quote }}
