"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Download, Printer, Mail, Copy, Check } from "lucide-react";
import { toast } from "sonner";
import { PaymentHistoryItem } from "@/types/payments";
import { format } from "date-fns";

interface PaymentReceiptProps {
  payment: PaymentHistoryItem;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function PaymentReceipt({ payment, open, onOpenChange }: PaymentReceiptProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const receiptText = formatReceiptText();
    await navigator.clipboard.writeText(receiptText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast.success("Receipt copied to clipboard");
  };

  const handlePrint = () => {
    window.print();
    toast.success("Opening print dialog...");
  };

  const handleDownload = () => {
    const receiptText = formatReceiptText();
    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(receiptText));
    element.setAttribute("download", `receipt-${payment.id}.txt`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    toast.success("Receipt downloaded");
  };

  const handleEmail = () => {
    const receiptText = encodeURIComponent(formatReceiptText());
    window.location.href = `mailto:?subject=Mbole Pay Receipt - ${payment.id}&body=${receiptText}`;
  };

  const formatReceiptText = () => {
    return `
╔══════════════════════════════════════━━━╗
║           MBOLE PAY - RECEIPT             ║
╚══════════════════════════════════════━━━╝

Receipt ID:          ${payment.id}
Transaction ID:      ${payment.transactionId || "N/A"}
Date:                ${format(new Date(payment.date), "PPpp")}

─────────────────────────────────────────

PAYMENT DETAILS

Amount:              ${payment.amount.toLocaleString()} ${payment.currency}
Provider:            ${payment.provider === "MTN_MOMO" ? "MTN Mobile Money" : "Orange Money"}
Phone Number:        ${maskPhoneNumber(payment.phoneNumber)}
Status:              ${payment.status}
Group:               ${payment.groupName || "N/A"}

─────────────────────────────────────────

DESCRIPTION

${payment.description || "No description provided"}

─────────────────────────────────────────

PAYMENT STATUS

Current Status:      ${getStatusLabel(payment.status)}
Timestamp:           ${format(new Date(payment.date), "yyyy-MM-dd HH:mm:ss")}

${payment.status === "FAILED" ? `Error:               ${payment.errorMessage || "Payment failed"}\n` : ""}

═════════════════════════════════════════

This is an automatic receipt generated by Mbole Pay.
For support, contact: support@mbolepay.com
Website: https://mbolepay.com

═════════════════════════════════════════
`;
  };

  const maskPhoneNumber = (phone: string) => {
    if (!phone || phone.length < 7) return "****";
    return `****${phone.slice(-4)}`;
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "COMPLETED":
        return "✓ Payment Successful";
      case "PENDING":
        return "⏳ Pending Confirmation";
      case "PROCESSING":
        return "🔄 Processing";
      case "FAILED":
        return "✗ Payment Failed";
      default:
        return status;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "COMPLETED":
        return "bg-green-100 text-green-900 dark:bg-green-900 dark:text-green-100";
      case "PENDING":
      case "PROCESSING":
        return "bg-amber-100 text-amber-900 dark:bg-amber-900 dark:text-amber-100";
      case "FAILED":
        return "bg-red-100 text-red-900 dark:bg-red-900 dark:text-red-100";
      default:
        return "bg-gray-100 text-gray-900 dark:bg-gray-900 dark:text-gray-100";
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Payment Receipt</DialogTitle>
          <DialogDescription>
            Receipt #{payment.id.slice(0, 8).toUpperCase()}
          </DialogDescription>
        </DialogHeader>

        {/* Receipt Display */}
        <div className="space-y-6">
          {/* Receipt Card */}
          <Card className="bg-white dark:bg-slate-950 border-2">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle>Payment Receipt</CardTitle>
                  <CardDescription>
                    {format(new Date(payment.date), "EEEE, MMMM d, yyyy")}
                  </CardDescription>
                </div>
                <Badge className={getStatusColor(payment.status)}>
                  {getStatusLabel(payment.status)}
                </Badge>
              </div>
            </CardHeader>

            <CardContent className="space-y-6">
              {/* Payment Details Grid */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Receipt ID
                  </p>
                  <p className="font-mono text-sm font-semibold">{payment.id}</p>
                </div>

                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Transaction ID
                  </p>
                  <p className="font-mono text-sm font-semibold">
                    {payment.transactionId || "N/A"}
                  </p>
                </div>

                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Date & Time
                  </p>
                  <p className="text-sm">
                    {format(new Date(payment.date), "PPpp")}
                  </p>
                </div>

                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Group
                  </p>
                  <p className="text-sm">{payment.groupName || "N/A"}</p>
                </div>

                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Provider
                  </p>
                  <p className="text-sm">
                    {payment.provider === "MTN_MOMO" ? "MTN Mobile Money" : "Orange Money"}
                  </p>
                </div>

                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    Payment Phone
                  </p>
                  <p className="text-sm font-mono">{maskPhoneNumber(payment.phoneNumber)}</p>
                </div>
              </div>

              {/* Amount */}
              <div className="rounded-lg bg-slate-100 dark:bg-slate-800 p-4">
                <p className="text-sm font-medium text-muted-foreground mb-1">
                  Amount Paid
                </p>
                <p className="text-3xl font-bold">
                  {payment.amount.toLocaleString()} <span className="text-lg">{payment.currency}</span>
                </p>
              </div>

              {/* Description */}
              {payment.description && (
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-2">
                    Description
                  </p>
                  <p className="text-sm bg-slate-50 dark:bg-slate-900 p-3 rounded">
                    {payment.description}
                  </p>
                </div>
              )}

              {/* Error Message if Failed */}
              {payment.status === "FAILED" && payment.errorMessage && (
                <Alert variant="destructive">
                  <AlertDescription>{payment.errorMessage}</AlertDescription>
                </Alert>
              )}

              {/* Footer */}
              <div className="text-center padding-y-4 border-t pt-4">
                <p className="text-xs text-muted-foreground">
                  This is an automatically generated receipt from Mbole Pay
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  For support: support@mbolepay.com
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Action Buttons */}
          <div className="flex gap-2 justify-end flex-wrap">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="gap-2"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy
                </>
              )}
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              className="gap-2"
            >
              <Download className="w-4 h-4" />
              Download
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handleEmail}
              className="gap-2"
            >
              <Mail className="w-4 h-4" />
              Email
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="gap-2"
            >
              <Printer className="w-4 h-4" />
              Print
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
