/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NjangiGroupFactory } from "./NjangiGroupFactory";
export * as factories from "./factories";
export { NjangiGroupFactory__factory } from "./factories/NjangiGroupFactory__factory";
