/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace NjangiGroupFactory {
  export type GroupRulesStruct = {
    name: string;
    contributionAmount: BigNumberish;
    frequency: string;
    payoutOrder: string;
    minMembers: BigNumberish;
    maxMembers: BigNumberish;
    creator: AddressLike;
    createdAt: BigNumberish;
  };

  export type GroupRulesStructOutput = [
    name: string,
    contributionAmount: bigint,
    frequency: string,
    payoutOrder: string,
    minMembers: bigint,
    maxMembers: bigint,
    creator: string,
    createdAt: bigint
  ] & {
    name: string;
    contributionAmount: bigint;
    frequency: string;
    payoutOrder: string;
    minMembers: bigint;
    maxMembers: bigint;
    creator: string;
    createdAt: bigint;
  };
}

export interface NjangiGroupFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCompletedCycles"
      | "getCycleRecipient"
      | "getGroupRules"
      | "isLocked"
      | "lockGroupRules"
      | "recordCycleComplete"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CycleCompleted" | "GroupRulesLocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCompletedCycles",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCycleRecipient",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupRules",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isLocked", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lockGroupRules",
    values: [
      BytesLike,
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCycleComplete",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCompletedCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCycleRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockGroupRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCycleComplete",
    data: BytesLike
  ): Result;
}

export namespace CycleCompletedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    cycle: BigNumberish,
    recipientId: BytesLike,
    amount: BigNumberish,
    memberCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    groupId: string,
    cycle: bigint,
    recipientId: string,
    amount: bigint,
    memberCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    groupId: string;
    cycle: bigint;
    recipientId: string;
    amount: bigint;
    memberCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupRulesLockedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    creator: AddressLike,
    contributionAmount: BigNumberish,
    frequency: string,
    payoutOrder: string
  ];
  export type OutputTuple = [
    groupId: string,
    creator: string,
    contributionAmount: bigint,
    frequency: string,
    payoutOrder: string
  ];
  export interface OutputObject {
    groupId: string;
    creator: string;
    contributionAmount: bigint;
    frequency: string;
    payoutOrder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NjangiGroupFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NjangiGroupFactory;
  waitForDeployment(): Promise<this>;

  interface: NjangiGroupFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCompletedCycles: TypedContractMethod<
    [groupId: BytesLike],
    [bigint],
    "view"
  >;

  getCycleRecipient: TypedContractMethod<
    [groupId: BytesLike, cycle: BigNumberish],
    [string],
    "view"
  >;

  getGroupRules: TypedContractMethod<
    [groupId: BytesLike],
    [NjangiGroupFactory.GroupRulesStructOutput],
    "view"
  >;

  isLocked: TypedContractMethod<[groupId: BytesLike], [boolean], "view">;

  lockGroupRules: TypedContractMethod<
    [
      groupId: BytesLike,
      name: string,
      contributionAmount: BigNumberish,
      frequency: string,
      payoutOrder: string,
      minMembers: BigNumberish,
      maxMembers: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordCycleComplete: TypedContractMethod<
    [
      groupId: BytesLike,
      cycle: BigNumberish,
      recipientId: BytesLike,
      amount: BigNumberish,
      memberCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCompletedCycles"
  ): TypedContractMethod<[groupId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCycleRecipient"
  ): TypedContractMethod<
    [groupId: BytesLike, cycle: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGroupRules"
  ): TypedContractMethod<
    [groupId: BytesLike],
    [NjangiGroupFactory.GroupRulesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[groupId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockGroupRules"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      name: string,
      contributionAmount: BigNumberish,
      frequency: string,
      payoutOrder: string,
      minMembers: BigNumberish,
      maxMembers: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCycleComplete"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      cycle: BigNumberish,
      recipientId: BytesLike,
      amount: BigNumberish,
      memberCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CycleCompleted"
  ): TypedContractEvent<
    CycleCompletedEvent.InputTuple,
    CycleCompletedEvent.OutputTuple,
    CycleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GroupRulesLocked"
  ): TypedContractEvent<
    GroupRulesLockedEvent.InputTuple,
    GroupRulesLockedEvent.OutputTuple,
    GroupRulesLockedEvent.OutputObject
  >;

  filters: {
    "CycleCompleted(bytes32,uint256,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;
    CycleCompleted: TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;

    "GroupRulesLocked(bytes32,address,uint256,string,string)": TypedContractEvent<
      GroupRulesLockedEvent.InputTuple,
      GroupRulesLockedEvent.OutputTuple,
      GroupRulesLockedEvent.OutputObject
    >;
    GroupRulesLocked: TypedContractEvent<
      GroupRulesLockedEvent.InputTuple,
      GroupRulesLockedEvent.OutputTuple,
      GroupRulesLockedEvent.OutputObject
    >;
  };
}
